# Generated by Django 4.2 on 2023-05-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='./course-1.jpg', upload_to='UploadedIages')),
                ('number_of_students', models.IntegerField()),
                ('course_duration', models.DurationField()),
                ('instructor', models.CharField(max_length=20)),
            ],
        ),
    ]
