# Generated by Django 4.2 on 2023-05-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcourse',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
