# Generated by Django 4.2 on 2023-05-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0002_popularcourse_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourse',
            name='description',
        ),
    ]
