# Generated by Django 4.2 on 2023-05-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0003_remove_popularcourse_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CoursesCat')),
                ('categories', models.CharField(max_length=20)),
                ('no_of_courses', models.IntegerField(default=0)),
            ],
        ),
    ]
